estimate_response: clean up and add options

diff --git a/scripts/estimate_response b/scripts/estimate_response
--- a/scripts/estimate_response
+++ b/scripts/estimate_response
@@ -1,62 +1,122 @@
 #!/bin/bash
 
-if [ $# -ne 4 ]; then 
-  echo 'usage: estimate_response dwi.mif mask.mif single-fibre_mask.mif response.mif'
-  echo ''
-  echo '  where:'
-  echo '    dwi.mif         input DWI images'
-  echo '    mask.mif        input brain mask'
-  echo '    sf_mask.mif     output mask of single-fibre voxels, as used in '
-  echo '                      the final response function estimation'
-  echo '    response.txt    output response function coefficients'
-  echo ''
+if [ $# -lt 4 ]; then 
+  cat <<EOD
 
+ usage: estimate_response [OPTIONS] dwi mask response
 
-else
-  
-  # set fail on error:
-  set -e
-  
-  # start with sharpest possible response function (i.e. SH decomposition of a flat disc):
-  echo "1,-1,1,-1,1" > __init_response.txt
-  mask="$2"
-  response=__init_response.txt
-  sf_mask="$3"
+ where:
 
-  # preload DWI with optimal stride (should also allow -shell option in due course)
-  dwiextract "$1" __dwi_high_shell.mif -force
-  # compute SH fit to DWI:
-  amp2sh __dwi_high_shell.mif __sh.mif -lmax 8 -force
-  
-  for iter in {1..5}; do
-  
-    # initial estimate of FOD, within brain mask:
-    dwi2fod __dwi_high_shell.mif -mask "$mask" "$response" __fod.mif -force 
-    
-    # extract 2 largest peaks into a 4D image split over volumes:
-    sh2peaks __fod.mif -mask "$mask" -num 2 "__p-[].mif" -force
-    
-    # compute ratio of peak squared amplitudes (admittedly not pretty, but clear enough):
-    # (note this computes the ratio peak1/(peak2+1) to prevent divide-by-zero if peak2 is zero)
-    mrcalc __p-0.mif 2 -pow __p-1.mif 2 -pow __p-2.mif 2 -pow -add -add __p-3.mif 2 -pow __p-4.mif 2 -pow __p-5.mif 2 -pow -add -add 1 -add -div __peak_ratio.mif -force
-    
-    # get mask of 300 voxels with largest peak1/peak2 ratio:
-    mrthreshold __peak_ratio.mif -top 300 "$sf_mask" -force
-    
-    # get mask of 10000 voxels with largest peak1/peak2 ratio to speed up in later iterations:
-    mrthreshold __peak_ratio.mif -top 10000 __mask_refined.mif -force
-  
-    mask=__mask_refined.mif
-    response="$4"
-    
-    # update estimate of response function within that mask, using FOD primary peak orientation:
-    sh2response __sh.mif "$sf_mask" "__p-[0:2].mif" "$response" -force
-    
-  done
-  
-  # clean up:
-  rm -f __dwi_high_shell.mif __init_response.txt __sh.mif __fod.mif __p-?.mif __peak_ratio.mif __mask_refined.mif
-  
+    dwi         input DWI images
+    mask        input brain mask
+    response    output text file containing response function coefficients
+
+ OPTIONS:
+
+    -niter N        set the number of iterations to use (default: 3)
+    -shell b        set the shell to select from the DWI (default: max)
+    -lmax L         set the maximum harmonic order to use (default: 8).
+    -sf mask        output the final mask of single-fibre voxels 
+    -peaks image    output image of peak orientations
+
+EOD
+
+  exit 1
 fi
+
+niter=3
+
+while [[ $# > 4 ]]; do
+  case $1 in 
+    -niter)
+      niter="$2";
+      shift
+      ;;
+    -shell)
+      shell="-shell $2";
+      shift
+      ;;
+    -lmax)
+      lmax="-lmax $2";
+      shift
+      ;;
+    -sf)
+      sf_mask="$2";
+      shift
+      ;;
+    -peaks)
+      output_peak="$2";
+      shift
+      ;;
+    *)
+      ;;
+  esac
+  shift
+done
+
+
+
+# set fail on error:
+set -e
+
+# import helper functions:
+. "$(dirname "$(which "$0")")"/__mrtrix_bash_helper_functions
+
+tmpdir=$(create_tmpdir)
+echo 'NOTE: temporary files will be placed in "'$tmpdir'"'
+  
+response="$3"
+dwi="$tmpdir"/dwi.mif
+sh="$tmpdir"/sh.mif
+fod="$tmpdir"/fod.mif
+peaks="$tmpdir"/peaks
+peak_ratio="$tmpdir"/peak_ratio.mif
+
+mask="$2"
+[ "x$sf_mask" == "x" ] && sf_mask="$tmpdir/sf_mask.mif"
+
+# start with sharpest possible response function (i.e. SH decomposition of a flat disc):
+echo "1,-1,1,-1,1" > "$response"
+
+# preload DWI with optimal stride (should also allow -shell option in due course)
+dwiextract "$1" $shell "$dwi" 
+
+# compute SH fit to DWI:
+amp2sh "$dwi" $lmax "$sh"
+
+for ((n=1; n<=niter; n++)); do
+
+  echo ''
+  echo "### iteration $n ###"
+
+  # initial estimate of FOD, within brain mask:
+  rm -f "$fod"
+  dwi2fod "$dwi" $lmax -mask "$mask" "$response" "$fod"
+  
+  # extract 2 largest peaks into a 4D image split over volumes:
+  rm -f "${peaks}"-?.mif
+  sh2peaks "$fod" -mask "$mask" -num 2 "${peaks}-[].mif" 
+  
+  # compute ratio of peak squared amplitudes (admittedly not pretty, but clear enough):
+  # (note this computes the ratio peak1/(peak2+1) to prevent divide-by-zero if peak2 is zero)
+  rm -f "$peak_ratio"
+  mrcalc "${peaks}-0.mif" 2 -pow "${peaks}-1.mif" 2 -pow "${peaks}-2.mif" 2 -pow -add -add "${peaks}-3.mif" 2 -pow "${peaks}-4.mif" 2 -pow "${peaks}-5.mif" 2 -pow -add -add 1 -add -div "$peak_ratio" -quiet
+  
+  # get mask of 300 voxels with largest peak1/peak2 ratio:
+  rm -f "$sf_mask"
+  mrthreshold "$peak_ratio" -top 300 "$sf_mask" -quiet
+  
+  # update estimate of response function within that mask, using FOD primary peak orientation:
+  rm -f "$response"
+  sh2response "$sh" "$sf_mask" "${peaks}-[0:2].mif" "$response" 
+
+  echo "current response coefficients: [ "$(cat "$response")" ]"
+  
+done
+
+[ "x$output_peak" != "x" ] && mrconvert "${peaks}-[0:2].mif" "$output_peak" 
+
+# clean up:
+rm -rf "$tmpdir"
 
 
